[[constraint]]
  name = "gopkg.in/src-d/go-mysql-server.v0"
  revision = "0966c4b25d0fa2bc6560feb977ff19cc3fcf1d18"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "github.com/src-d/go-git"
  revision = "0106daba16494c33d330168e38c8a610b7a9b32c"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.0.0"

[[override]]
  name = "golang.org/x/sys"
  source = "github.com/golang/sys"
  revision = "f0d5e33068cb57c22a181f5df0ffda885309eb5a"

[[override]]
  name = "golang.org/x/crypto"
  source = "github.com/golang/crypto"

[[override]]
  name = "golang.org/x/text"
  source = "github.com/golang/text"

[[override]]
  name = "golang.org/x/net"
  source = "github.com/golang/net"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[override]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.7.2"

[[constraint]]
  name = "gopkg.in/bblfsh/client-go.v3"
  version = "3.2.0"

[[override]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "1.16.1"

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v2"
  version = "2.14.2"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "^2.7.0"

[[override]]
  name = "github.com/pilosa/pilosa"
  version = "1.3.0"

[[override]]
  name = "github.com/pilosa/go-pilosa"
  version = "1.3.0"

[[override]]
  name = "github.com/src-d/go-oniguruma"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-vitess.v1"
  version = "1.6.0"

[[constraint]]
  name = "github.com/hhatto/gocloc"
  revision = "c5379f7427f9a9a5bec11accdf8a2ef7fa414d3e"

[prune]
  [[prune.project]]
    name = "gopkg.in/src-d/go-mysql-server.v0"
    go-tests = true
    unused-packages = true
  [[prune.project]]
    name = "gopkg.in/src-d/go-git.v4"
    go-tests = true
    non-go = true
    unused-packages = true
  [[prune.project]]
    name = "gopkg.in/src-d/enry.v1"
    go-tests = true
    non-go = true
    unused-packages = true
  [[prune.project]]
    name = "gopkg.in/bblfsh/sdk.v2"
    go-tests = true
    non-go = true
    unused-packages = true
